### ISSUE TITLE
How to setup to work with Jellyfin

### ISSUE THREAD

**Issue by milanmdev** [daniel-widrick/zap2it-GuideScraping#18]
How can I set up this repository to work with Jellyfin? I assume I need to automate this script to run every 10 minutes or something like that.

I am using `Ubuntu 20.4 LTS` & `Jellyfin 10.7.7`.

**Comment by daniel-widrick** [comment]
I run the script once a day via cron. Jellyfin is then configured to look at the output file for its guide data. 10 minutes is likely too often. The script tries to download two weeks of programming.

**Comment by milanmdev** [comment]
I see. Is the modal presented in the image below supposed to display all the channels mapped to the file?
![image](https://user-images.githubusercontent.com/29466935/147491843-9d3b4c3f-fcff-4b8b-bcd9-c8a443e7b219.png)

**Comment by daniel-widrick** [comment]
Do you have logs from jellyfin processing your guide.xmltv file by chance?

**Comment by milanmdev** [comment]
I figured out how to do it, thanks anyways!
