### ISSUE TITLE
Any example how runs?

### ISSUE THREAD

**Issue by Toei79** [daniel-widrick/zap2it-GuideScraping#23]
im fully new on this i have basic skill on linux, just try run scrip .sh one but i get errors i suppose to fill somethings on script right?

i add my username and password values country USA, and zipcode still get errors , i guess its something that i dont fill on script,

any example?

whats the ini file? one that ends with .dist i fill my info in that one. thanks

**Comment by daniel-widrick** [comment]
> whats the ini file? one that ends with .dist i fill my info in that one

Fill this file out than copy or move or rename it to config.ini. the config.ini.dist file is an example for config.ini

Try that out and then if you have trouble come on back and post any specific errors/etc you get.

**Comment by Toei79** [comment]
![image](https://user-images.githubusercontent.com/79808610/155862397-6f9ec13f-36dd-4fd5-98f2-c34cd12013c1.png)

hi i get this i fill  config.ini with my user name (email) and pasword , zipcode.

**Comment by daniel-widrick** [comment]
I'll address this later in the code/release but it appears it currently expects `config.ini` to be named `zap2itconfig.ini`

For the time being can rename the config.ini to zap2itconfig.ini and test again? sorry about the confusion

**Comment by Toei79** [comment]
![02-28-2022 (150337)](https://user-images.githubusercontent.com/79808610/156050836-417f8c3d-a201-4d16-935f-c507749f5656.jpg)

fix that still get errors. only data that i add was to zap2itconfig.ini

**Comment by daniel-widrick** [comment]
That error suggests to me an authentication problem. I'll try to dig into more soon.

**Comment by melendyk** [comment]
> ![02-28-2022 (150337)](https://user-images.githubusercontent.com/79808610/156050836-417f8c3d-a201-4d16-935f-c507749f5656.jpg)
> 
> fix that still get errors. only data that i add was to zap2itconfig.ini

I've recreated your error by using invalid password with my my user id, so make sure you are using valid credentials in the .ini file.
Also, to be safe, I run the command this way explicitly including all options/parameters:
python3 zap2it-GuideScrape.py -c zap2itconfig.ini -o xmlfile.xml

**Comment by Toei79** [comment]
i still getting same thing
![03-03-2022 (233633)](https://user-images.githubusercontent.com/79808610/156700425-7b6cfcf8-7831-49de-a5a3-fd78f0bdd7b9.jpg)

![2022-03-03_23-42-22](https://user-images.githubusercontent.com/79808610/156700971-0ab530c9-840b-497a-b131-c95ef594ce85.jpg)

this its the listings page? just to be sure. if i changed password and run again also i run new parameters
https://tvlistings.zap2it.com/?aid=gapzap

**Comment by melendyk** [comment]
That should be all you need... if you can log into that page with your email (username) and password, it should work...
![Screenshot from 2022-03-04 08-11-27](https://user-images.githubusercontent.com/99462020/156779836-5022af25-e15d-4a01-8ddf-a677890c59a7.png)

**Comment by Toei79** [comment]
> That should be all you need... if you can log into that page with your email (username) and password, it should work... ![Screenshot from 2022-03-04 08-11-27](https://user-images.githubusercontent.com/99462020/156779836-5022af25-e15d-4a01-8ddf-a677890c59a7.png)

thanks thats why i asked  an example. its all that i need.

my error was i only place my username and not email.  my username for zap was name on my email.

i did charly instead charly@gmail.com

its running fine now thanks!

**Comment by daniel-widrick** [comment]
I have updated the config.ini.dist to be more reflective of this: https://github.com/daniel-widrick/zap2it-GuideScraping/commit/facaf0c15684fbb5a6d4dd97442e92a7d9b61d44

**Comment by Toei79** [comment]
Question how you use guide?

i try using it with tivimate but its only detecting the first  channel. of epg
im using hdhomerun with tivimate.  and loading epg on tivimate.

**Comment by melendyk** [comment]
Sorry I can't help you with that... I use it to load guide in Jellyfin server (which uses my hdhomerun) and just use jellyfin clients.  Why not just use hdhomerun app if that's all your trying to do is watch tv and have a guide... the app shows a guide without having to load anything specific.

**Comment by Toei79** [comment]
Thanks i prefer tivimate plus i guess you need pay for record with hdhomerun.

**Comment by daniel-widrick** [comment]
I've never used tivimate but, I have recorded tv shows with this guide, my hdhomerun, and jellyfin.

**Comment by Toei79** [comment]
actually its fine, i mean, i know a github script that get same style xml data, , one that extract epg from hdhommerun devices, i was hoping this one was different, but guess not, issue its tivimate .

issue for what i remember can be fixed adding channel list to beginning of the xml file.

![03-08-2022 (220051)](https://user-images.githubusercontent.com/79808610/157364429-2aa07fc4-61e1-4787-bdeb-e93ffcf3006a.jpg)

for example like this.  

im been thinking there its two kind of xml epg data but i never found some info about it.

**Comment by Toei79** [comment]
well i found some way , maybe sharing this its useful for any to read issues section.

i add epg to my tvheadend, then i able to use it add it to tivimate, kinda like after tvheadend process the epg , it make it workeable for tivimate , and yea structure changes when epg its loaded from tvheadend.

the only issue is icons.

**Comment by djlzotz** [comment]
I am having the following authentication error. Is there anything I should know about special characters or the like. I suspect they may be causing issues.

python3 zap2it-GuideScrape.py -c zap2itconfig.ini -o xmlguid.xmltv
Namespace(configfile='zap2itconfig.ini', outputfile='xmlguid.xmltv', language=None, findid=False)
Loading config:  zap2itconfig.ini  and outputting:  xmlguid.xmltv
Traceback (most recent call last):
  File "/docker/zap2it/zap2it-GuideScraping-main/zap2it-GuideScrape.py", line 315, in <module>
    guide.BuildGuide()
  File "/docker/zap2it/zap2it-GuideScraping-main/zap2it-GuideScrape.py", line 243, in BuildGuide
    self.Authenticate()
  File "/docker/zap2it/zap2it-GuideScraping-main/zap2it-GuideScrape.py", line 35, in Authenticate
    authResponse = urllib.request.urlopen(authRequest).read()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
