### ISSUE TITLE
How to use this correctly?

### ISSUE THREAD

**Issue by somerandomuser1** [daniel-widrick/zap2it-GuideScraping#34]
I hate to be that guy, but I have been googling for the past 2 hours trying to find some kind of info, literally ANYTHING on how to use this, and there is nothing.

The Readme is basically useless. (I'm sorry to be blunt, but it is)

The only thing this script seems to do at all is the -h for the help section.

Every single other command simply returns 4-6 errors depending on the command, and then nothing.

I have already edited my config file to be correct, it should "just work" based on what I've read, but it doesn't.

This is the error I get everytime.

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\zap2it-GuideScraping-20220901\zap2it-GuideScrape.py", line 301, in <module>
    guide = Zap2ItGuideScrape(optConfigFile,optGuideFile)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\zap2it-GuideScraping-20220901\zap2it-GuideScrape.py", line 16, in __init__
    self.lang = self.config.get("prefs","lang")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'prefs'

**Comment by Toei79** [comment]
where you running it?

its python , idk if you need any files  to install, looks you runs on windows maybe yea windows support linux but maybe some its lost


still running fine for me , you need fill the .ini file with login account and other few data more
then run it

i guess big issue when you no too expert its lack of real examples most code on github lack of that real examples ,  im kinda like you and take me time.

**Comment by daniel-widrick** [comment]
Sorry for the late response.

These look like the errors I get if I run the script in a directory that doesn't have a "zap2itconfig.ini" file.

EG: If someone were to attempt to change the contents of zap2itconfig.ini.dist but not rename or copy the .dist file to a .ini file
