### ISSUE TITLE
tvheadend epg grabber

### ISSUE THREAD

**Issue by th0ma7** [daniel-widrick/zap2it-GuideScraping#8]
Heads-up, I asked the tvheadend developpers for pointers (or help) on how you code could be migrated to become a new default epg grabber in tvheadend.  That allows to use the built-in functionalities within tvheadend to use methods of capturing EPG (using OTA scanning, flat-file, url download, etc.).

FYI:
https://tvheadend.org/issues/6039

**Comment by anurodhp** [comment]
If you use one of the external grabbers in tvheadend this is the script is use to load it up

python zap2it-GuideScrape.py
cat /var/lib/hts/.hts/tvheadend/zap2it-GuideScraping/xmlguide.xmltv  | soca
t - UNIX-CONNECT:/home/hts/.hts/tvheadend/epggrab/xmltv.sock
